services:
  sms:
    container_name: elmariam-sms-svc
    image: ranckosolutionsinc/elmariam-sms-service:1.0.0
    # build: ./
    restart: always
    ports:
      - 7879:7879
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - NODE_ENV=${NODE_ENV}
      - UJUMBESMS_API_KEY=${UJUMBESMS_API_KEY}
      - UJUMBESMS_API_URL=${UJUMBESMS_API_URL}
      - UJUMBESMS_ACCOUNT_EMAIL=${UJUMBESMS_ACCOUNT_EMAIL}
    networks:
      - elmariam-network

networks:
  elmariam-network:
    name: elmariam
    driver: bridge
    external: true
