services:
  gateway:
    container_name: elmariam-api-gateway
    image: ranckosolutionsinc/elmariam-api-gateway:1.0.0
    build: ./
    restart: always
    ports:
      - 8009:8009
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gateway.otienoobogeandcompany.com`)"
      # - "traefik.http.routers.api.entrypoints=websecure"
      # - "traefik.http.routers.api.tls=true"  # if using certresolver
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.services.gateway.loadbalancer.server.port=8009"  
    networks:
      - elmariam-network

networks:
  elmariam-network:
    name: elmariam
    driver: bridge
    external: true
