services:

  rabbitmq:
    container_name: elmariam-queue
    image: rabbitmq:3.12-management
    restart: always
    ports:
     - 5672:5672
     - 15672:15672 
    environment:
     - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}     
     - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
     - RABBITMQ_DEFAULT_VHOST=default_vhost
    networks:
      - elmariam   

networks:
  elmariam:
    name: elmariam
    driver: bridge
    external: true
