apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../auth-service.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../auth-service.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: ACCESS_SECRET
              valueFrom:
                configMapKeyRef:
                  key: ACCESS_SECRET
                  name: auth-env
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: auth-env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: auth-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: auth-env
            - name: REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: REFRESH_SECRET
                  name: auth-env
          image: ranckosolutionsinc/hotel-elmariam-auth-service:1.0.0
          name: hotel-elmariam-auth-svc
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
