apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../auth-service.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../auth-service.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - image: mongo:4.2
          name: hotel-elmariam-mongo-db
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: hotel-elmiriam-mongodb-data
      restartPolicy: Always
      volumes:
        - name: hotel-elmiriam-mongodb-data
          persistentVolumeClaim:
            claimName: hotel-elmiriam-mongodb-data
