apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../bar-service.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bar
  name: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bar
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../bar-service.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: bar
    spec:
      containers:
        - env:
            - name: ACCESS_SECRET
              valueFrom:
                configMapKeyRef:
                  key: ACCESS_SECRET
                  name: env
            - name: AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTH_API_URL
                  name: env
            - name: CLOUDINARY_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: CLOUDINARY_API_KEY
                  name: env
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                configMapKeyRef:
                  key: CLOUDINARY_API_SECRET
                  name: env
            - name: CLOUDINARY_CLOUDNAME
              valueFrom:
                configMapKeyRef:
                  key: CLOUDINARY_CLOUDNAME
                  name: env
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: env
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY
                  name: env
            - name: MINIO_API_HOST
              valueFrom:
                configMapKeyRef:
                  key: MINIO_API_HOST
                  name: env
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_KEY
                  name: env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: env
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: env
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PORT
                  name: env
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_USERNAME
                  name: env
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_VHOST
                  name: env
            - name: REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: REFRESH_SECRET
                  name: env
          image: ranckosolutionsinc/hotel-elmariam-bar-service:v1.0-alpha
          name: hotel-elmariam-bar-svc
      restartPolicy: Always
