apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f hotel-service.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: hotel
  name: hotel
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 8003
  selector:
    io.kompose.service: hotel
