apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f hotel-service.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: hotel
  name: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hotel
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f hotel-service.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: hotel
    spec:
      containers:
        - env:
            - name: ACCESS_SECRET
              valueFrom:
                configMapKeyRef:
                  key: ACCESS_SECRET
                  name: hotel-env
            - name: AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTH_API_URL
                  name: hotel-env
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: hotel-env
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: hotel-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: hotel-env
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: hotel-env
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PASSWORD
                  name: hotel-env
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PORT
                  name: hotel-env
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_USERNAME
                  name: hotel-env
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_VHOST
                  name: hotel-env
            - name: REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: REFRESH_SECRET
                  name: hotel-env
          image: ranckosolutionsinc/hotel-elmariam-hotel-service:v1.0-alpha
          name: hotel-elmariam-hotel-svc
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
